# Generated by Django 5.2.14 on 2026-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentitem',
            old_name='rent_duration_minutes',
            new_name='rent_duration_days',
        ),
    ]
