# Generated by Django 5.2.14 on 2026-05-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_rent_duration_minutes_rentitem_rent_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwedMoneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cleared_at', models.DateTimeField(auto_now_add=True)),
                ('owed_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.owedmoney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_money_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
